# SPDX-FileCopyrightText: 2024 Tillitis AB <tillitis.se>
# SPDX-License-Identifier: BSD-2-Clause
version = 1

[[annotations]]
path = ".github/workflows/*"
SPDX-FileCopyrightText = "2024 Tillitis AB <tillitis.se>"
SPDX-License-Identifier = "BSD-2-Clause"

[[annotations]]
path = [
     "authorized_keys",
     "ca_key.pub",
     "host_ed25519",
     "host_ed25519.pub",
     ".editorconfig",
     ".gitignore",
     ".golangci.yml",
     "README.md",
     "go.mod",
     "go.sum",
]
SPDX-FileCopyrightText = "2024 Tillitis AB <tillitis.se>"
SPDX-License-Identifier = "BSD-2-Clause"
